{
 "title": "New dashboard",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Consumo CPU gNMIc",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "rate(container_cpu_usage_seconds_total{container_label_clab_node_name=\"gNMIc\"}[1m]) * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Consumo CPU Nokia Switch",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "rate(container_cpu_usage_seconds_total{container_label_clab_node_name=\"srlswitch2\"}[1m]) * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Out Multicast Pkts",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "irate(srl_nokia_interfaces_interface_statistics_out_multicast_packets{subscription_name=\"srl-if-stats\"}[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "In Multicast Pkts",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "irate(srl_nokia_interfaces_interface_statistics_in_multicast_packets{subscription_name=\"srl-if-stats\"}[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "In Unicast Pkts",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "rate(srl_nokia_interfaces_interface_statistics_in_unicast_packets{subscription_name=\"srl-if-stats\"}[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Out Unicast Pkts",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "rate(srl_nokia_interfaces_interface_statistics_out_unicast_packets{subscription_name=\"srl-if-stats\"}[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "In Discard Pkts",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "irate(srl_nokia_interfaces_interface_statistics_in_discarded_packets{subscription_name=\"srl-if-stats\"}[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "In Error Pkts",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "irate(srl_nokia_interfaces_interface_statistics_in_error_packets{subscription_name=\"srl-if-stats\"}[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Traffic Rate In Octets",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "rate(srl_nokia_interfaces_interface_statistics_in_octets{subscription_name=\"srl-if-stats\"}[1m]) * 8",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Traffic rate In",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "srl_nokia_interfaces_interface_traffic_rate_in_bps{subscription_name=\"srl-if-stats\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}