username: admin
password: NokiaSrl1!
insecure: false
skip-verify: true
encoding: json_ietf
timeout: 10s

targets:
  srlswitch2:
    address: srlswitch2:57400
    
subscriptions:    
  srl-if-stats:
    mode: stream
    stream-mode: sample
    sample-interval: 5s
    paths:
      - /interface[name=ethernet-1/4]/statistics/in-discarded-packets
      - /interface[name=ethernet-1/4]/statistics/in-error-packets
      - /interface[name=ethernet-1/4]/statistics/in-multicast-packets
      - /interface[name=ethernet-1/4]/statistics/in-unicast-packets
      - /interface[name=ethernet-1/4]/statistics/in-broadcast-packets
      - /interface[name=ethernet-1/4]/statistics/in-octets
      - /interface[name=ethernet-1/4]/statistics/out-discarded-packets
      - /interface[name=ethernet-1/4]/statistics/out-error-packets
      - /interface[name=ethernet-1/4]/statistics/out-multicast-packets
      - /interface[name=ethernet-1/4]/statistics/out-unicast-packets
      - /interface[name=ethernet-1/4]/statistics/out-broadcast-packets
      - /interface[name=ethernet-1/4]/statistics/out-octets
      
outputs:
  file_output:
    type: file
    filename: /data/if-stats-nokia.json
    format: json
    split-events: true      
