username: admin
password: NokiaSrl1!
insecure: false
skip-verify: true
encoding: json_ietf
timeout: 10s

targets:
  srlswitch2:
    address: srlswitch2:57400
    
subscriptions:    
  
  srl-if-stats-stream:
    mode: stream
    stream-mode: sample
    sample-interval: 5s
    paths:
      - /interface[name=ethernet-1/*]/statistics/in-unicast-packets
      - /interface[name=ethernet-1/*]/statistics/in-multicast-packets
      - /interface[name=ethernet-1/*]/traffic-rate/in-bps
      - /interface[name=ethernet-1/*]/statistics/in-discarded-packets
      - /interface[name=ethernet-1/*]/statistics/in-error-packets
      - /interface[name=ethernet-1/*]/statistics/out-unicast-packets
      - /interface[name=ethernet-1/*]/statistics/out-multicast-packets
      - /interface[name=ethernet-1/*]/statistics/out-discarded-packets
      - /interface[name=ethernet-1/*]/statistics/out-error-packets
      - /interface[name=ethernet-1/*]/traffic-rate/out-bps
              
outputs:
  
  prom-output:
    type: prometheus
    listen: :9273
    export-timestamps: true    # Preserva timestamp del dispositivo [[prometheus_output]]
    override-timestamps: false # No reemplazar con tiempo de scrape
    debug: true
