username: admin
password: NokiaSrl1!
insecure: false
skip-verify: true
encoding: json_ietf
timeout: 10s

targets:
  srlswitch2:
    address: srlswitch2:57400
    
subscriptions:    
  
  srl-if-stats-stream:
    mode: stream
    stream-mode: sample
    sample-interval: 5s
    paths:
      - /interface[name=ethernet-1/*]/statistics/in-unicast-packets
      - /interface[name=ethernet-1/*]/statistics/in-octets
      - /interface[name=ethernet-1/*]/statistics/in-multicast-packets
      - /interface[name=ethernet-1/*]/traffic-rate/in-bps
      - /interface[name=ethernet-1/*]/statistics/in-discarded-packets
      - /interface[name=ethernet-1/*]/statistics/in-error-packets
      - /interface[name=ethernet-1/*]/statistics/out-unicast-packets
      - /interface[name=ethernet-1/*]/statistics/out-octets
      - /interface[name=ethernet-1/*]/statistics/out-multicast-packets
      - /interface[name=ethernet-1/*]/statistics/out-discarded-packets
      - /interface[name=ethernet-1/*]/statistics/out-error-packets
      - /interface[name=ethernet-1/*]/traffic-rate/out-bps
              
outputs:
  
  victoria-output:
    type: prometheus_write
    url: http://victoriametrics:8428/api/v1/write
    interval: 5s
    buffer-size: 1000
    max-time-series-per-write: 500
    timeout: 10s
    debug: false
